export { StewardAuth } from "./auth.ts";
export type {
  SessionStorage,
  StewardAuthConfig,
  StewardAuthExchangeResponse,
  StewardAuthResult,
  StewardEmailResult,
  StewardFarcasterLoginConfig,
  StewardFarcasterLoginPayload,
  StewardIdentityClaims,
  StewardIdentityTokenResult,
  StewardLinkedAccount,
  StewardMfaRequiredResult,
  StewardOAuthConfig,
  StewardOAuthResult,
  StewardProviders,
  StewardRecoveryCodeStatus,
  StewardRecoveryCodesResult,
  StewardSession,
  StewardSmsMfaEnrollResult,
  StewardSmsMfaStatus,
  StewardSmsMfaVerifyResult,
  StewardSmsOtpResult,
  StewardTelegramLoginConfig,
  StewardTelegramLoginPayload,
  StewardTenantInfo,
  StewardTenantMembership,
  StewardTestAccountLoginOptions,
  StewardTotpEnrollResult,
  StewardTotpStatus,
  StewardTotpVerifyResult,
  StewardUser,
  StewardWhatsAppOtpResult,
} from "./auth-types.ts";
export type {
  AgentPolicyRuleCreate,
  AgentPolicyRuleUpdate,
  BatchAgentSpec,
  BatchCreateResult,
  CreateTradeSessionInput,
  CreateTradeSessionResult,
  CreateWalletResult,
  GetAddressesResult,
  GetBalanceResult,
  GetHistoryResult,
  GlobalWalletActionConfirmation,
  GlobalWalletApproveResult,
  GlobalWalletAppSummary,
  GlobalWalletConsent,
  GlobalWalletConsentRequest,
  GlobalWalletRpcResult,
  GlobalWalletTransactionScan,
  HyperliquidOrderResult,
  HyperliquidSubmitOrderInput,
  QuorumSignerCredential,
  SignAuthorizationOptions,
  SignMessageOptions,
  SignMessageResult,
  SignRawHashInput,
  SignRawHashResult,
  SignTransactionInput,
  SignTransactionOptions,
  SignTransactionResult,
  SignTypedDataOptions,
  SignUserOperationOptions,
  StewardClientConfig,
  StewardErrorResponse,
  StewardHistoryEntry,
  StewardPendingApproval,
  StewardSignerAuthOptions,
  TransactionLifecycleEventType,
  TransactionLifecycleUpdateInput,
  TransactionReplaceInput,
  UserAccountsResult,
  UserAccountUnlinkResult,
  UserEthereumWalletLinkNonce,
  UserEthereumWalletLinkResult,
  UserLinkedAccount,
  UserOAuthAccountLinkResult,
  UserPhoneAccountLinkResult,
  UserPhoneAccountLinkSendResult,
  UserSocialAccountLinkChallenge,
  UserSocialAccountLinkResult,
  UserSolanaWalletLinkNonce,
  UserSolanaWalletLinkResult,
  WalletActionOptions,
} from "./client.ts";
export { StewardApiError, StewardClient } from "./client.ts";
// Generated from the API's OpenAPI document (single source of truth). Run
// `bun run openapi` in @stwd/api to regenerate. Exposed under explicit aliases so
// downstream code can derive request/response types from the live API contract.
export type {
  components as ApiComponents,
  operations as ApiOperations,
  paths as ApiPaths,
} from "./generated/api-types.ts";
// v0.4.0 - Tenant config, dashboard, approvals, webhooks
export type {
  AgentAccountCapability,
  AgentAccountSummary,
  AgentAccountWallet,
  AgentBalance,
  AgentDashboardResponse,
  AgentIdentity,
  AgentKeyQuorum,
  AgentKeyQuorumCreate,
  AgentKeyQuorumStatus,
  AgentKeyQuorumUpdate,
  AgentSigner,
  AgentSignerCreate,
  AgentSignerCreateResult,
  AgentSignerStatus,
  AgentSignerSubjectType,
  AgentSignerType,
  AgentSignerUpdate,
  AgentSpendSummary,
  AllowedChainsConfig,
  ApiResponse,
  ApprovalQueueEntry,
  ApprovalStats,
  ApprovedAddressesConfig,
  AuditLogEntry,
  AuditLogResponse,
  AuditSummaryResponse,
  AutoApprovalRule,
  AutoApproveConfig,
  ChainFamily,
  ChainIdentifier,
  ConditionSet,
  ConditionSetConfig,
  ConditionSetCreate,
  ConditionSetItem,
  ConditionSetItemInput,
  ConditionSetUpdate,
  CreateRoutePayload,
  CreateSecretPayload,
  ExportKeyResult,
  GasSponsorshipMode,
  GasSponsorshipProvider,
  GasSponsorshipState,
  InjectAs,
  Intent,
  IntentCreate,
  IntentListOptions,
  IntentStatus,
  IntentType,
  PolicyResult,
  PolicyRule,
  PolicySimulateInput,
  PolicySimulateResult,
  PolicyTemplate,
  PolicyTemplateCreate,
  PolicyTemplateUpdate,
  PolicyType,
  RateLimitConfig,
  RouteRecord,
  SecretRecord,
  SignRequest,
  SpendingLimitConfig,
  SponsoredGasSpendEntry,
  SponsoredGasSpendSummary,
  TenantAccessAllowlistEntry,
  TenantAccessAllowlistEntryInput,
  TenantAccessAllowlistEntryType,
  TenantAuthAbuseConfig,
  TenantControlPlaneConfig,
  TenantGasSponsorshipConfig,
  TenantMembership,
  TimeWindowConfig,
  TxRecord,
  TxStatus,
  UpdateRoutePayload,
  UserAccountCapability,
  UserAccountSummary,
  UserAccountWallet,
  UserPushPlatform,
  UserPushProvider,
  UserPushSubscription,
  UserPushSubscriptionInput,
  UserPushSubscriptionListResult,
  UserPushSubscriptionResult,
  UserWalletRecoveryRestoreResult,
  UserWalletRecoverySetupResult,
  WebhookConfig,
  WebhookDelivery,
  WebhookEventType,
} from "./types.ts";
export {
  CHAINS,
  chainFromCaip2,
  chainFromNumeric,
  fromCaip2,
  SUPPORTED_CHAINS,
  toCaip2,
  WEBHOOK_EVENT_TYPES,
} from "./types.ts";
export {
  signWebhookPayload,
  type VerifyWebhookOptions,
  type VerifyWebhookResult,
  verifyWebhookSignature,
} from "./webhook-verify.ts";
