import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import {
  chmodSync,
  existsSync,
  lstatSync,
  readFileSync,
  renameSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";

export type InitOptions = {
  envPath?: string;
  force?: boolean;
  runMigrations?: boolean;
  databaseUrl?: string;
  apiUrl?: string;
};

export type InitResult = {
  envPath: string;
  created: boolean;
  migrations: "ran" | "skipped";
  auditSigningKeyFormat: "hex-seed";
};

function hex(bytes: number): string {
  return randomBytes(bytes).toString("hex");
}

function platformKey(): string {
  return `stw_platform_${hex(24)}`;
}

function renderEnv(options: InitOptions): string {
  const platform = platformKey();
  const scopes = JSON.stringify({
    [platform]: ["platform:write", "platform:tenant:create"],
  });
  // Generate the postgres password ONCE and interpolate the SAME value into the
  // default DATABASE_URL so a fresh install is internally consistent: postgres
  // boots with this password and api/proxy/migrations connect with the same
  // one. An explicit --database-url override wins (operator supplies matching
  // credentials themselves).
  const postgresPassword = hex(24);
  // Defaults target the enterprise-reference compose network (service DNS names),
  // not host loopback: the generated file is consumed by that compose profile,
  // where an explicit DATABASE_URL overrides compose's `postgres:5432` fallback
  // and the API port is not published to the host (only Caddy's 80/443 are).
  // Standalone/local users override with --database-url / --api-url.
  const databaseUrl =
    options.databaseUrl ?? `postgresql://steward:${postgresPassword}@postgres:5432/steward`;
  return [
    "# Generated by steward init. Review before production use.",
    "# Host defaults (postgres/redis/steward.localhost) target the",
    "# enterprise-reference compose network. Override with --database-url",
    "# / --api-url for standalone or host-local runs.",
    "NODE_ENV=production",
    "PORT=3200",
    "STEWARD_API_URL=" + (options.apiUrl ?? "https://steward.localhost"),
    "DATABASE_URL=" + databaseUrl,
    "POSTGRES_DB=steward",
    "POSTGRES_USER=steward",
    "POSTGRES_PASSWORD=" + postgresPassword,
    "STEWARD_MASTER_PASSWORD=" + hex(32),
    "STEWARD_JWT_SECRET=" + hex(32),
    "STEWARD_EMAIL_CODE_SECRET=" + hex(32),
    // Provider execution authorization key rotation list. The active first
    // entry signs and all entries verify. Keep this separate from JWT material.
    "STEWARD_EXECUTION_AUTH_SECRET=v1:" + hex(32),
    "STEWARD_KDF_SALT=" + hex(32),
    // This env sets NODE_ENV=production with no STEWARD_KMS_PROVIDER, so the
    // vault resolves to `local` custody (plaintext key in app memory at sign
    // time). The production custody gate refuses to boot local mode unless the
    // posture is acknowledged. The ack is deliberately emitted COMMENTED OUT:
    // an operator who accepts local custody uncomments it, recording the
    // decision explicitly and auditably (SEC-120).
    "# Custody posture: no STEWARD_KMS_PROVIDER is set, so the vault runs in",
    "# `local` mode (plaintext key in app memory at sign time). The production",
    "# custody gate refuses to boot local mode unless the posture is explicitly",
    "# acknowledged. To accept local custody, uncomment the line below (records",
    "# the decision). To harden instead, set STEWARD_KMS_PROVIDER=aws|pkcs11.",
    "# See docs/security/custody-posture.md.",
    "# STEWARD_ACK_LOCAL_CUSTODY=true",
    "STEWARD_AUDIT_HMAC_KEY=" + hex(32),
    "# Raw 32-byte Ed25519 seed hex; supported by packages/api/src/services/audit-checkpoint.ts.",
    "STEWARD_AUDIT_SIGNING_KEY=" + hex(32),
    "STEWARD_PLATFORM_KEY=" + platform,
    "STEWARD_PLATFORM_KEYS=" + platform,
    "STEWARD_PLATFORM_KEY_SCOPES='" + scopes + "'",
    "STEWARD_TENANT_ID=",
    "STEWARD_TOKEN=",
    "# Tenant API key (X-Steward-Key). Machine credential the CLI falls back to",
    "# for non-interactive agent/secret/policy/approval calls when STEWARD_TOKEN is unset.",
    "STEWARD_TENANT_KEY=",
    "RPC_URL=https://mainnet.base.org",
    "CHAIN_ID=8453",
    "REDIS_URL=redis://redis:6379",
    "STEWARD_PROXY_REQUEST_SIGNING_SECRETS=" + hex(32),
    "APP_URL=https://steward.localhost",
    "PASSKEY_RP_NAME=Steward",
    "PASSKEY_RP_ID=steward.localhost",
    "PASSKEY_ORIGIN=https://steward.localhost",
    "",
  ].join("\n");
}

function readEnvValue(source: string, key: string): string | undefined {
  for (const line of source.split(/\r?\n/)) {
    const idx = line.indexOf("=");
    if (idx <= 0) continue;
    if (line.slice(0, idx) === key) return line.slice(idx + 1).replace(/^'|'$/g, "");
  }
  return undefined;
}

/**
 * Atomically write `contents` to `envPath` with mode 0600.
 *
 * We write to a fresh temp file created 0600 in the SAME directory, then
 * renameSync it into place. This guarantees:
 *   - the final file is always mode 0600, even when replacing (--force) an
 *     existing world-readable (0644) file: chmod-on-existing would race and
 *     leave a window where secrets are readable; a fresh 0600 temp never is.
 *   - the replacement is atomic (rename within a filesystem), so a reader never
 *     observes a partially-written secrets file.
 *
 * Refuses to operate on a symlink envPath: following it could clobber an
 * arbitrary attacker-chosen target with our secrets, or leave secrets at a
 * path with attacker-controlled perms.
 */
function writeEnvAtomic(envPath: string, contents: string): void {
  if (existsSync(envPath)) {
    const stat = lstatSync(envPath);
    if (stat.isSymbolicLink()) {
      throw new Error(
        `${envPath} is a symlink; refusing to write secrets through it. Remove it and re-run.`,
      );
    }
  }
  const dir = dirname(envPath);
  const tmpPath = resolve(dir, `.steward-env-${randomBytes(12).toString("hex")}.tmp`);
  // { mode: 0o600 } is applied by the OS at creation (subject to umask, which
  // can only REMOVE bits), so the temp file is never group/other readable.
  // chmodSync afterwards makes 0600 exact regardless of umask.
  writeFileSync(tmpPath, contents, { mode: 0o600, flag: "wx" });
  try {
    chmodSync(tmpPath, 0o600);
    renameSync(tmpPath, envPath);
  } catch (err) {
    try {
      if (existsSync(tmpPath)) unlinkSync(tmpPath);
    } catch {
      // best-effort cleanup; surface the original error
    }
    throw err;
  }
}

export function runInit(options: InitOptions = {}): InitResult {
  const envPath = resolve(options.envPath ?? ".env");
  if (existsSync(envPath) && !options.force) {
    throw new Error(`${envPath} already exists. Re-run with --force to replace it.`);
  }

  const previous = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
  if (!previous.includes("STEWARD_AUDIT_SIGNING_KEY=") || options.force) {
    writeEnvAtomic(envPath, renderEnv(options));
  }

  let migrations: InitResult["migrations"] = "skipped";
  if (options.runMigrations) {
    const envSource = readFileSync(envPath, "utf8");
    const databaseUrl = options.databaseUrl ?? readEnvValue(envSource, "DATABASE_URL");
    // Resolve the migrator against THIS CLI's install tree and run it with the
    // current runtime. A CWD-relative path would execute whatever
    // packages/db/src/migrate.ts exists beneath the operator's (possibly
    // attacker-writable) working directory, with every generated secret below
    // in its environment.
    const result = spawnSync(process.execPath, [join(import.meta.dir, "../../db/src/migrate.ts")], {
      env: {
        ...process.env,
        DATABASE_URL: databaseUrl ?? process.env.DATABASE_URL ?? "",
        // STEWARD_ALLOW_INSECURE_DB is inherited only when the operator set it
        // explicitly — never defaulted on, so the production DB-TLS gate
        // (packages/db/src/client.ts) is not silently bypassed.
      },
      stdio: "inherit",
    });
    if (result.status !== 0) throw new Error("Database migrations failed");
    migrations = "ran";
  }

  return { envPath, created: true, migrations, auditSigningKeyFormat: "hex-seed" };
}
